"""Small, explicit design system. No selectors into framework-generated IDs."""

CSS = """
:root{--ink:#202d40;--muted:#657289;--line:#e3e8ef;--blue:#3458d4;--wash:#f5f7fb}
body{background:#f7f8fb;color:var(--ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:15px}
.nicegui-content{padding:0;gap:0} .q-btn{text-transform:none;font-weight:600;letter-spacing:0;font-size:13px;border-radius:8px;min-height:38px;box-shadow:none}
.q-btn__content{flex-wrap:nowrap;gap:6px}.app-drawer .nav-button{color:#647086!important}.app-drawer .nav-button.selected{color:#284dc3!important}.app-drawer .queue-mini{color:#3e4e68!important}
.q-btn:before{box-shadow:none!important}.q-field--outlined .q-field__control{border-radius:8px;background:white}.q-field--outlined .q-field__control:before{border-color:#dce3ed}.q-field__label{color:#657289}.q-field{font-size:14px}
a{color:var(--blue)}button:focus-visible,a:focus-visible{outline:3px solid #8ba4fa;outline-offset:3px}
.app-header{background:#fff;color:var(--ink);border-bottom:1px solid var(--line);height:64px;padding:0 28px;box-shadow:none;gap:14px}
.brand{font-size:17px;font-weight:750;letter-spacing:-.4px}.brand-mark{width:32px;height:32px;background:var(--blue);border-radius:10px;color:white;display:grid;place-items:center;font-size:20px}
.environment{border:1px solid #e0e6ee;border-radius:5px;padding:3px 7px;font-size:10px;letter-spacing:1px;font-weight:700;color:#657289}
.app-drawer{background:#f1f3f8;border-right:1px solid var(--line)}.drawer-inner{padding:24px 14px;height:100%;gap:6px}.nav-button{justify-content:flex-start;width:100%;color:#647086;padding:0 14px;min-height:43px}.nav-button .q-btn__content{justify-content:flex-start;gap:12px}.nav-button.selected{background:#e3e9fc;color:#284dc3}
.drawer-caption{font-size:11px;color:#8590a2;line-height:1.6}.queue-mini{width:100%;text-align:left;padding:10px 12px;border-radius:9px;cursor:pointer;border:1px solid transparent}.queue-mini:hover{background:white}.queue-mini.selected{background:white;border-color:#dce3f0}.queue-mini .q-btn__content{justify-content:flex-start;text-align:left}
.page{width:100%;max-width:1500px;margin:auto;padding:32px 40px 48px;gap:24px}.page-title{font-size:29px;font-weight:720;line-height:1.15;letter-spacing:-1px;margin:0}.subtitle{color:var(--muted);font-size:14px;line-height:1.6}.eyebrow{font-size:10px;font-weight:750;letter-spacing:1.6px;color:#8290a6;text-transform:uppercase}.section-title{font-size:16px;font-weight:700;letter-spacing:-.2px}.muted{color:var(--muted);font-size:13px}.small{font-size:12px}.panel{width:100%;background:white;border:1px solid var(--line);border-radius:13px;padding:22px;box-shadow:0 2px 5px #25345403;gap:16px}.flush-panel{padding:0;overflow:hidden}.toolbar{width:100%;align-items:center;gap:12px;flex-wrap:wrap}.grow{flex:1;min-width:0}.heading-row{width:100%;align-items:center;justify-content:space-between;gap:16px}.stats{display:flex;gap:30px;align-items:center}.stat-number{font-size:25px;font-weight:700;letter-spacing:-1px}.stat-label{font-size:12px;color:var(--muted)}
.badge{display:inline-flex;align-items:center;border-radius:5px;padding:4px 8px;background:#edf1f6;color:#59677c;font-size:11px;font-weight:600;white-space:normal}.badge.green{background:#e8f5ee;color:#247354}.badge.amber{background:#fff3dc;color:#925f13}.badge.blue{background:#edf1ff;color:#3458d4}.badge.red{background:#fdebed;color:#a83f4c}
.inbox-head,.inbox-row{display:grid;grid-template-columns:1.1fr 1.05fr 1.7fr 145px;gap:20px;align-items:center;padding:18px 22px;width:100%}.inbox-head{padding-top:12px;padding-bottom:12px;background:#fafbfe;font-size:11px;color:#8792a4;letter-spacing:.7px;text-transform:uppercase}.inbox-row{border-top:1px solid #eef1f6}.inbox-row:hover{background:#fafbff}.guest-name{font-weight:680;font-size:15px}.inbox-row .muted{font-size:12px}.inbox-row .q-btn{white-space:normal}.dot{width:6px;height:6px;border-radius:50%;background:#3458d4}
.next-action{background:#edf2ff;border:1px solid #dce5ff;border-radius:11px;padding:16px 20px;display:flex;gap:20px;align-items:center;width:100%}.next-title{font-size:15px;font-weight:700;color:#2847a2}.notice{width:100%;border-radius:8px;padding:11px 14px;font-size:13px;line-height:1.55;background:#fff7e6;color:#875d1c}.notice.error{background:#fff0f1;color:#a13c4b}.notice.success{background:#eaf6ef;color:#276e50}.notice.info{background:#f0f4fa;color:#556882}
.workspace-grid{display:grid;grid-template-columns:minmax(0, .85fr) minmax(0,1.2fr);gap:24px;width:100%;align-items:start}.context-column,.action-column{min-width:0;width:100%;gap:20px}.message{font-size:14px;line-height:1.75;white-space:pre-wrap;overflow-wrap:anywhere;color:#354258}.message-meta{font-size:11px;color:#8491a3}.outbound{border-left:3px solid #b5c4f2;padding-left:12px}.detail-row{display:flex;gap:10px;justify-content:space-between;width:100%;border-bottom:1px solid #f0f2f6;padding:8px 0;font-size:13px}.detail-row .value{text-align:right;font-weight:500;max-width:65%;overflow-wrap:anywhere}.q-expansion-item{width:100%}.q-expansion-item .q-item{padding-left:0;padding-right:0;min-height:42px;font-size:13px;color:#516079}.q-expansion-item__content{padding:8px 0 12px}.segmented{background:#edf0f6;border-radius:9px;padding:4px;display:flex;gap:3px;width:100%}.segmented .q-btn{flex:1;color:#798599;min-height:35px}.segmented .q-btn.active{background:white;color:#2c4ba9;box-shadow:0 1px 4px #33405c12}.seating-card{border:1px solid #dfe6f3;border-radius:10px;padding:16px;gap:10px;width:100%;background:#fbfcff}.seating-card.chosen{border-color:#9db0ec;background:#f7f9ff}.booking-summary{background:#f6f8fc;border-radius:9px;padding:13px 16px;width:100%;font-size:13px;line-height:1.65}.action-bar{display:flex;gap:9px;align-items:center;flex-wrap:wrap;border-top:1px solid var(--line);padding-top:15px;width:100%;background:white}.reply-editor textarea{line-height:1.8!important;font-size:14px!important;min-height:300px!important}.reply-editor{width:100%}.dialog-card{width:680px;max-width:calc(100vw - 32px)!important;border-radius:15px!important;padding:28px;gap:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;width:100%}.form-grid>*{min-width:0}.history-entry{border-left:2px solid #e5eaf4;padding:0 0 18px 16px;width:100%}.service-row{padding:18px 22px;border-top:1px solid #edf1f6;width:100%;gap:9px}.table-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;width:100%}.table-unit{border:1px solid #e1e6ed;border-radius:7px;padding:9px;text-align:center;font-size:12px}.table-unit.preview{background:#eaf0ff;border-color:#9fb4ef}.table-unit.busy{background:#fff1e7}.mobile-context,.mobile-environment{display:none}.timeline-wrap{overflow:auto;width:100%}.timeline{border-collapse:collapse;font-size:11px;min-width:850px;width:100%;table-layout:fixed}.timeline th,.timeline td{border:1px solid #e3e8ef;padding:8px 3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;height:42px}.timeline th:first-child{width:95px;position:sticky;left:0;background:#fafbff}.timeline .confirmed{background:#dfe8ff;color:#284eac}.timeline .held{background:#ffefd2;color:#7a571e}.busy-screen{position:fixed;inset:64px 0 0 0;background:#f8faffaa;z-index:5000;display:flex;align-items:center;justify-content:center;gap:12px;color:#3458d4;backdrop-filter:blur(1px)}
@media(min-width:901px){.action-column .action-bar{position:sticky;bottom:12px;z-index:2;box-shadow:0 8px 0 8px white}}
@media(max-width:1150px){.page{padding:28px 24px}.inbox-head,.inbox-row{grid-template-columns:1fr 1fr 1.2fr 120px;gap:12px}.workspace-grid{gap:16px}.panel{padding:17px}}
@media(max-width:900px){.desktop-stages{display:none!important}.workspace-grid{grid-template-columns:1fr}.mobile-context{display:flex}.workspace-grid .context-column{display:none}.workspace-grid.request-mode .context-column{display:flex}.workspace-grid.request-mode .action-column{display:none}.inbox-head{display:none}.inbox-row{grid-template-columns:1fr 1fr}.inbox-row>div:nth-child(3){grid-column:1}.inbox-row>button{grid-column:2}.stats{gap:20px}}
@media(max-width:600px){.app-header .brand-mark,.environment-badge{display:none}.mobile-environment{display:inline-flex}.toolbar>.q-field:first-child{flex-basis:100%;width:100%}.toolbar>.q-field{flex:1;min-width:120px}.stats{align-items:flex-start}.stat-label{min-height:32px;line-height:1.5}.app-header{padding:0 14px;gap:8px}.brand{font-size:15px}.header-note{display:none}.page{padding:22px 16px;gap:18px}.page-title{font-size:25px}.heading-row{align-items:flex-start}.next-action{align-items:flex-start;gap:10px;flex-direction:column;padding:15px}.next-action>.q-btn{width:100%}.panel{padding:16px}.flush-panel{padding:0}.stats{gap:22px}.stat-number{font-size:22px}.form-grid{grid-template-columns:1fr}.dialog-card{padding:22px}.inbox-row{padding:16px;gap:10px}.action-bar .q-btn{flex:1}.table-grid{grid-template-columns:repeat(2,1fr)}.q-dialog__inner{padding:12px}}
"""
