"""Operator study timer. Records only what the operator does; never generates times."""

from __future__ import annotations

import json

import streamlit as st

from ..study.harness import CHECKLIST, METHOD_LABELS, StudyStore, load_cases, sessions_csv, status


@st.cache_resource(show_spinner=False)
def _store() -> StudyStore:
    return StudyStore()


def render_study_view() -> None:
    store = _store()
    cases = {c.id: c for c in load_cases()}
    s = status(store)
    st.markdown("# Operator study")
    st.caption("12 cases × 3 methods = 36 timed sessions with counterbalanced order. Timing starts when the case is "
               "first opened and stops when the simulated booking action/notes and a reviewed initial response are "
               "ready. Model wait is logged separately. No times are generated by this tool; nothing is sent.")
    st.markdown(f"**Status:** {s['status']} · {s['sessions_completed']}/{s['sessions_planned']} sessions completed")
    rows = store.sessions()
    pending = [r for r in rows if r["status"] != "completed"]
    default = pending[0]["seq"] if pending else rows[0]["seq"]
    seq = st.selectbox("Session", [r["seq"] for r in rows], index=[r["seq"] for r in rows].index(default),
                       format_func=lambda q: (lambda r: f"#{r['seq']} round {r['round']} · {r['case_id']} · "
                                              f"{METHOD_LABELS[r['method']]} · {r['status']}")(rows[q - 1]))
    r = rows[seq - 1]
    c = cases[r["case_id"]]
    left, right = st.columns([1.1, 1], gap="medium")
    with left:
        st.markdown(f"### {c.id}: {c.title}")
        st.markdown(f"**Method:** {METHOD_LABELS[r['method']]}  \n**Source scenario:** {c.source}  \n**Brief:** {c.brief}")
        st.caption("Materials: docs/study/PROTOCOL.md, METHOD_TEMPLATE_ONLY.md, METHOD_STRUCTURED_LLM.md, "
                   "AVAILABILITY_SHEET.md. Expected outcome is shown only after finishing.")
        state = store.state(seq)
        st.markdown(f"**Timer state:** {state}")
        b = st.columns(3) + st.columns(3)  # two rows so labels are not truncated
        actions = [("start", "Start"), ("pause", "Pause"), ("resume", "Resume"), ("wait_start", "Model wait"),
                   ("wait_end", "Wait done"), ("finish", "Finish")]
        from ..study.harness import TRANSITIONS
        for col, (kind, label) in zip(b, actions):
            if col.button(label, key=f"t_{kind}_{seq}", disabled=kind not in TRANSITIONS[state], width="stretch"):
                store.record(seq, kind)
                st.rerun()
        d = store.durations(seq)
        if d["active_s"] is not None:
            st.success(f"Active {d['active_s']} s (elapsed {d['elapsed_s']} s, paused {d['paused_s']} s, "
                       f"model wait {d['model_wait_s']} s).")
            st.markdown(f"**Expected outcome:** {c.expected_outcome}")
    with right:
        chk = json.loads(r["checklist"] or "{}")
        with st.form(f"study_{seq}"):
            op = st.text_input("Operator", value=r["operator"] or "")
            fam = st.selectbox("Familiarity with this case", ["first exposure", "seen in an earlier method",
                                                                "seen during development"],
                               index=0 if not r["familiarity"] else
                               ["first exposure", "seen in an earlier method", "seen during development"].index(r["familiarity"]))
            new_chk = {k: st.checkbox(lbl, value=bool(chk.get(k)), key=f"c_{k}_{seq}") for k, lbl in CHECKLIST}
            n1, n2, n3 = st.columns(3)
            corr = n1.number_input("Corrections", 0, 99, int(r["corrections"] or 0))
            errs = n2.number_input("Errors", 0, 99, int(r["errors"] or 0))
            inc = n3.number_input("Incomplete reqs", 0, 99, int(r["incomplete_requirements"] or 0))
            notes = st.text_area("Notes", value=r["notes"] or "", height=80)
            art = st.text_input("Output artifact path (notes/response saved for this session)",
                                value=r["artifact_path"] or "")
            if st.form_submit_button("Save session record"):
                store.update(seq, operator=op, familiarity=fam, checklist=new_chk, corrections=corr, errors=errs,
                             incomplete_requirements=inc, notes=notes, artifact_path=art)
                st.rerun()
    st.download_button("Export sessions CSV", sessions_csv(store), file_name="study_sessions.csv", mime="text/csv")
