[theme]
base = "light"
primaryColor = "#2747C9"
backgroundColor = "#FAF9F6"
secondaryBackgroundColor = "#F0F2F5"
textColor = "#202734"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
